### ISSUE TITLE
 Requirements list Python 2.7

### ISSUE THREAD

**Issue by FarrandTom** [SeldonIO/seldon-deploy-sdk#12]
The requirements in the README list Python 2.7 and 3.4+. 

I do not believe the SDK works with Python 2.7 and will give invalid syntax errors. Please could the README be updated to reflect this.

**Comment by agrski** [comment]
This was an issue with the swagger-codegen base templates, with no option to override those via mustache variables.
I've fixed this in [this PR](https://github.com/SeldonIO/seldon-deploy-sdk/pull/32).
