### ISSUE TITLE
Include `requests` in the dependencies of the pip package

### ISSUE THREAD

**Issue by FarrandTom** [SeldonIO/seldon-deploy-sdk#2]
Currently, have to install `requests` separately after installing the seldon-deploy-sdk. I think `requests` should be included in the dependencies of the seldon-deploy-sdk as it is required for the OIDCAuthentication.

**Comment by agrski** [comment]
Closing as fixed [here](https://github.com/SeldonIO/seldon-deploy-sdk/commit/f44e85099ef1b2f0d7e285efa0023787059fcaa7#diff-b72f6e5561c432513e240838ae1eeb3f85237fa3ed5d701ad4c3be2a55c57b9dR4)
