### ISSUE TITLE
Typo in the Readme

### ISSUE THREAD

**Issue by FarrandTom** [SeldonIO/seldon-deploy-sdk#9]
Currently the usage section has the following:
Usage
The Python version of the SDK includes support for sommon common authentication workflows.

This should be corrected to:
Usage
The Python version of the SDK includes support for common authentication workflows.

Removing "sommon".

**Comment by RafalSkolasinski** [comment]
Hi @FarrandTom,

If you have time you can craft a PR to fix it, happy to just click "merge" ; - )

**Comment by agrski** [comment]
Closing as fixed [here](https://github.com/SeldonIO/seldon-deploy-sdk/commit/fbb45a08c347f0b7e652f9858075ee2a6e1ef75d#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5)
